### ISSUE TITLE
Question about Zettelkasten

### ISSUE THREAD

**Issue by akessner** [alefore/weblog#1]
Hi, do you still use zettlekasten? I saw a redit post of yours from about a year ago, and I'm curious if you still find it as useful on your day to day work, such as edge or other projects.

**Comment by Vasallius** [comment]
hi @akessner, what reddit post where you pertaining to? and yes, i still use zettelkasten

**Comment by akessner** [comment]
The comment here.

https://amp.reddit.com/r/Zettelkasten/comments/gcac3v/does_it_worth_it_for_me_engineerdeveloper/

I noticed you didn't have many updates to this GitHub repo so I was
curious. Thanks!

**Comment by alefore** [comment]
Yeah, I still use Zettelkasten, almost every day. I mostly use it for:

1. Tracking/productivity stuff (organizing the day). This isn't exactly what Zettelkasten is meant for, but it works great for me anyway.
2. Writing fiction. Right now I'm doing a project to write 5 micro stories per week.
3. Keep notes about my friends and coworkers. Every time I have an important phone call, I write a short summary.
4. Writing notes about topics I'm researching. Lately I've been writing about diabetes, gingko trees, and brutalistic architecture. I guess you can see that I spent a while working on my article about [Leadership at Google](https://github.com/alefore/weblog/blob/master/leadership.md) (this is generated directly from my Zettelkasten).

Hope that helps. I should probably regenerate all the graphs linked to from my Zettelkasten article.
